---
- hosts: all
  become: yes
  tasks:
    - name: install remi
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    - name: install httpd
      yum: name=httpd state=installed
    - name: install mariadb
      yum: name={{ item }} state=installed
      with_items:
        - mariadb
        - mariadb-devel
        - mariadb-server
    - name: install php
      yum: pkg={{ item }} state=installed enablerepo=remi,remi-php56
      with_items:
        - php
        - php-cli
        - php-common
        - php-devel
        - php-fpm
        - php-json
        - php-mbstring
        - php-mcrypt
        - php-mysql
        - php-pdo
        - php-process
        - php-xml

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes
    - name: be sure mariadb is running and enabled
      service: name=mariadb state=running enabled=yes
