---
- hosts: all
  become: yes
  tasks:
    - name: install httpd
      yum: name=httpd state=installed

    - name: install utils
      yum: name={{ item }} state=installed
      with_items:
        - git
        - zip
        - unzip

    - name: install repos
      yum: name={{ item }} state=installed
      with_items:
        - epel-release
        - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

    - name: install mariadb
      yum: name={{ item }} state=installed
      with_items:
        - mariadb
        - mariadb-devel
        - mariadb-server

    - name: install php
      yum: pkg={{ item }} state=latest enablerepo=remi,remi-php71
      with_items:
        - php
        - php-devel
        - php-fpm
        - php-mbstring
        - php-pdo
        - php-mcrypt
        - php-mysql
        - php-mysqlnd
        - php-opcache
        - php-xml
        - php-cli
        - php-common
        - php-json
        - php-process
        - php-intl

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes

    - name: be sure mariadb is running and enabled
      service: name=mariadb state=running enabled=yes
